server {
    listen 80;
    server_name bancochile.local;

    root /workspace/web;
    index index.html;

    # Permite servir el symlink web/data -> ../output
    disable_symlinks off;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
